### ISSUE TITLE
RPi installation instructions do not work

### ISSUE THREAD

**Issue by NickWaterton** [ev3dev/grx#14]
I am looking for a simple graphics package for RPi3. This looks promising, but the installation instructions are incorrect, and there are no instructions for building from source.

Specifically for RPi the file https://github.com/ev3dev/grx/raw/ev3dev-stretch/.travis/ev3dev-archive-keyring.gpg does not exist, so you can’t install from the repository.

I cloned the git, but none of the standard build tools work, and I don’t know the dependencies.

I could spend a lot of time working it out, but why not make it easy? Just provide some build/install instructions.

**Comment by NickWaterton** [comment]
BTW this is what I get (checked out the stretch branch).
```
pi@raspberrypi:~/grx/build $ cmake -L -DCMAKE_BUILD_TYPE="Release" ..
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find GLibGenMarshal (missing: GLIB_GENMARSHAL_EXE)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGLibGenMarshal.cmake:32 (find_package_handle_standard_args)
  src/CMakeLists.txt:215 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/pi/grx/build/CMakeFiles/CMakeOutput.log".
-- Cache values
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_INSTALL_PREFIX:PATH=/usr/local
GRX_DEBUG:STRING=OFF
GRX_ENABLE_DOC:BOOL=Yes
GRX_PLUGIN_GTK3:BOOL=Yes
GRX_PLUGIN_LINUXFB:BOOL=Yes
```

**Comment by dlech** [comment]
Thanks for the feedback. Did you see this? https://github.com/ev3dev/grx/wiki/Compiling-the-code#advanced-command-line

**Comment by NickWaterton** [comment]
No, that is well hidden. Thanks!

I have VSCode on my Windows setup, but not on my server (it’s headless). This is a good starting point though.

I’ll give it a try, thanks for the fast response.

**Comment by NickWaterton** [comment]
Ok, there is no ./setup.deb.py file. Any way you can just tell me what the dependencies are?

**Comment by dlech** [comment]
you can find the build dependencies here: https://github.com/ev3dev/grx/blob/ev3dev-stretch/debian/control

**Comment by NickWaterton** [comment]
So after an hour of guess the dependency hell, I got it to compile and install (14 warnings, but anyway).

Still can’t run any python examples.

```
/usr/local/lib/grx-3.0/examples/python/boxes.py
Traceback (most recent call last):
  File "/usr/local/lib/grx-3.0/examples/python/boxes.py", line 24, in <module>
    gi.require_version('Grx', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Grx not available
```

Looks like another missing dependency, but I don’t know what.

Any suggestions?

**Comment by dlech** [comment]
Did you set all of the environment variables?

https://github.com/ev3dev/grx/wiki/Running-Programs#environment-variables

**Comment by NickWaterton** [comment]
Ah Ha!

So - success! got boxes.py to run. Great - just got to get console-runner to install now...

Note: you need to run ldconfig as well before the libraries are found.

Thanks for all the help. Hopefully this will do what I'm looking for.

**Comment by dlech** [comment]
IMHO, it would be easier to just install everything from the debian packages. Here is the missing keyring. You can unzip it an save it in `/etc/apt/trusted.gpg.d/`. 

[keyring.tar.gz](https://github.com/ev3dev/grx/files/2824733/keyring.tar.gz)

**Comment by dlech** [comment]
Or you can just grab the .deb files and install them with `sudo dpkg -i <filename>` (and `sudo apt install -f` to fix missing dependencies).

e.g. http://archive.ev3dev.org/raspbian/pool/main/c/console-runner/
